<?php

use Drupal\Core\Link;
use Drupal\Core\Url;

module_load_include('inc', 'outlook_events', 'outlook_events.auth');



/**
 * Returns the date range().
 */
function outlook_events_week_range($date) {
  $ts = strtotime($date);
  $start = (date('w', $ts) == 0) ? $ts : strtotime('now', $ts);
  return array(
    date('c', $start),
    date('c', strtotime('next month', $start)),
  );
}

function _get_weekdays($date) {
  list($day, $month, $year) = explode("-", $date);

  // Get the weekday of the given date
  $wkday = date('l',mktime('0','0','0', $month, $day, $year));

  switch($wkday) {
    case 'Saturday': $numDaysToSat = 0; break;
    case 'Sunday': $numDaysToSat = 1; break;
    case 'Monday': $numDaysToSat = 2; break;
    case 'Tuesday': $numDaysToSat = 3; break;
    case 'Wednesday': $numDaysToSat = 4; break;
    case 'Thursday': $numDaysToSat = 5; break;
    case 'Friday': $numDaysToSat = 6; break;
  }

    // Timestamp of the saturday for that week
  $monday = mktime('0','0','0', $month, $day-$numDaysToSat, $year);

  $seconds_in_a_day = 86400;

  // Get date for 7 days from Monday (inclusive)
  for($i=2; $i<7; $i++)
  {
    $dates[$i] = date('Y-m-d',$monday+($seconds_in_a_day*$i));
  }
  return $dates;
}

function get_outlook_events($range = '+7day') {

  $page = pager_default_initialize(30, 7);
  $page_offset = $page * 7;
  $event_rows = array();
  $week_days = _get_weekdays(date('d-m-Y', strtotime(" +$page_offset day")));
    list($start_date, $end_date) = outlook_events_week_range(date('Y-m-d H:i:s'));
  $dates = outlook_events_date_range($start_date, $end_date);
  //$events = outlook_events_list();
  $get_outlook_account_list = get_outlook_account_list();
  $scheduler = array();
  $i = 0;
 foreach ($get_outlook_account_list as $account) {
  $events = outlook_events_list($account);
         foreach ($events as $event) {
        $start = $event->Start;
        $end = $event->End;
        $subject = $event->Subject;
        $location = $event->Location;
        $organizer = $event->Organizer->Mailbox->Name;
        if (in_array(date('Y-m-d', strtotime($start)), $dates)) {
          date_default_timezone_set('Asia/Kolkata');
          $scheduler[$i]['title'] = $subject;
          $scheduler[$i]['organizer'] = $organizer;
          $scheduler[$i]['location'] = $location;
          $scheduler[$i]['start_ist'] = date('Y-m-d H:i:s', strtotime($start));
          $scheduler[$i]['end_ist'] = date('Y-m-d H:i:s', strtotime($end));
          $i++;
        }

      }

}
return $scheduler;
}

function get_outlook_account_list() {
$query = \Drupal::database()->select('outlook_events', 'oe');
$query->fields('oe', ['uid','mail','password']);
$results = $query->execute()->fetchAll();
return $results;
}


function get_outlook_calendar() {
//select records from table
    $query = \Drupal::database()->select('outlook_events', 'oe');
      $query->fields('oe', ['id','mail']);
      $results = $query->execute()->fetchAll();
        $rows=array();
    foreach($results as $data){
        $delete = Url::fromUserInput('/outlook-account/form/delete/'.$data->id);
        $edit   = Url::fromUserInput('/outlook-account/form/edit/?num='.$data->id);
      //print the data from table
             $rows[] = array(
            'id' =>$data->id,
                'mail' => $data->mail,
             'opt' =>    \Drupal::l('Delete', $delete),
             'opt1' =>    \Drupal::l('Edit', $edit),
            );
}
return $rows;
}